// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

type NewComment struct {
	UserID    string  `json:"userID"`
	ReplyToID *string `json:"replyToID"`
	Content   string  `json:"content"`
	Agent     string  `json:"agent"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
